# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict


class E2EFetchSpanScoreRequest(TypedDict):
    project_name: str
    trace_id: str
    span_id: str
