# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional
from typing_extensions import NotRequired


class ErrorResponse(TypedDict):
    error: str
    message: NotRequired[Optional[str]]
