# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, List

from .trace_info import TraceInfo


class TriggerRootSpanRulesRequest(TypedDict):
    traces: List[TraceInfo]
