# generated by datamodel-codegen:
#   filename:  .openapi.json
#   timestamp: 2025-08-06T01:21:41+00:00

from __future__ import annotations
from typing import Annotated, Any, Dict, List, Optional, Union
from pydantic import BaseModel, ConfigDict, Field
from datetime import datetime


class CheckExperimentTypeJudgmentType(BaseModel):
    eval_name: Annotated[str, Field(title="Eval Name")]
    project_name: Annotated[str, Field(title="Project Name")]
    is_trace: Annotated[bool, Field(title="Is Trace")]


class EvalRunNameCheckJudgmentType(BaseModel):
    eval_name: Annotated[str, Field(title="Eval Name")]
    project_name: Annotated[str, Field(title="Project Name")]


class EvalResultsFetchJudgmentType(BaseModel):
    eval_name: Annotated[str, Field(title="Eval Name")]
    project_name: Annotated[str, Field(title="Project Name")]


class DatasetFetchJudgmentType(BaseModel):
    dataset_alias: Annotated[str, Field(title="Dataset Alias")]
    project_name: Annotated[str, Field(title="Project Name")]


class DatasetFetchStatsByProjectJudgmentType(BaseModel):
    project_name: Annotated[str, Field(title="Project Name")]


class TraceSaveJudgmentType(BaseModel):
    project_name: Annotated[str, Field(title="Project Name")]
    trace_id: Annotated[str, Field(title="Trace Id")]
    name: Annotated[str, Field(title="Name")]
    created_at: Annotated[str, Field(title="Created At")]
    duration: Annotated[float, Field(title="Duration")]
    offline_mode: Annotated[Optional[bool], Field(title="Offline Mode")] = False
    has_notification: Annotated[Optional[bool], Field(title="Has Notification")] = False
    customer_id: Annotated[Optional[str], Field(title="Customer Id")] = None
    tags: Annotated[Optional[List[str]], Field(title="Tags")] = None
    metadata: Annotated[Optional[Dict[str, Any]], Field(title="Metadata")] = None
    update_id: Annotated[Optional[int], Field(title="Update Id")] = 1


class TraceFetchJudgmentType(BaseModel):
    trace_id: Annotated[str, Field(title="Trace Id")]


class EvaluationRunsBatchRequestJudgmentType(BaseModel):
    organization_id: Annotated[str, Field(title="Organization Id")]
    evaluation_entries: Annotated[
        List[Dict[str, Any]], Field(title="Evaluation Entries")
    ]


class ProjectAddJudgmentType(BaseModel):
    project_name: Annotated[str, Field(title="Project Name")]


class ProjectAddResponseJudgmentType(BaseModel):
    project_id: Annotated[str, Field(title="Project Id")]


class ScorerExistsRequestJudgmentType(BaseModel):
    name: Annotated[str, Field(title="Name")]


class ScorerExistsResponseJudgmentType(BaseModel):
    exists: Annotated[bool, Field(title="Exists")]


class SavePromptScorerRequestJudgmentType(BaseModel):
    name: Annotated[str, Field(title="Name")]
    prompt: Annotated[str, Field(title="Prompt")]
    options: Annotated[Optional[Dict[str, float]], Field(title="Options")] = None


class SavePromptScorerResponseJudgmentType(BaseModel):
    message: Annotated[str, Field(title="Message")]
    name: Annotated[str, Field(title="Name")]


class FetchPromptScorerRequestJudgmentType(BaseModel):
    name: Annotated[str, Field(title="Name")]


class ResolveProjectNameRequestJudgmentType(BaseModel):
    project_name: Annotated[str, Field(title="Project Name")]


class ResolveProjectNameResponseJudgmentType(BaseModel):
    project_id: Annotated[str, Field(title="Project Id")]


class ValidationErrorJudgmentType(BaseModel):
    loc: Annotated[List[Union[str, int]], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class ExampleJudgmentType(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    example_id: Annotated[str, Field(title="Example Id")]
    created_at: Annotated[str, Field(title="Created At")]
    name: Annotated[Optional[str], Field(title="Name")] = None


class ScorerConfigJudgmentType(BaseModel):
    score_type: Annotated[str, Field(title="Score Type")]
    name: Annotated[Optional[str], Field(title="Name")] = None
    threshold: Annotated[Optional[float], Field(title="Threshold")] = 0.5
    strict_mode: Annotated[Optional[bool], Field(title="Strict Mode")] = False
    required_params: Annotated[Optional[List[str]], Field(title="Required Params")] = []
    kwargs: Annotated[Optional[Dict[str, Any]], Field(title="Kwargs")] = None


class SpanBatchItemJudgmentType(BaseModel):
    span_id: Annotated[str, Field(title="Span Id")]
    trace_id: Annotated[str, Field(title="Trace Id")]
    function: Annotated[str, Field(title="Function")]
    depth: Annotated[int, Field(title="Depth")]
    created_at: Annotated[Any, Field(title="Created At")] = None
    parent_span_id: Annotated[Optional[str], Field(title="Parent Span Id")] = None
    span_type: Annotated[Optional[str], Field(title="Span Type")] = "span"
    inputs: Annotated[Optional[Dict[str, Any]], Field(title="Inputs")] = None
    output: Annotated[Any, Field(title="Output")] = None
    error: Annotated[Optional[Dict[str, Any]], Field(title="Error")] = None
    usage: Annotated[Optional[Dict[str, Any]], Field(title="Usage")] = None
    duration: Annotated[Optional[float], Field(title="Duration")] = None
    expected_tools: Annotated[
        Optional[List[Dict[str, Any]]], Field(title="Expected Tools")
    ] = None
    additional_metadata: Annotated[
        Optional[Dict[str, Any]], Field(title="Additional Metadata")
    ] = None
    has_evaluation: Annotated[Optional[bool], Field(title="Has Evaluation")] = False
    agent_name: Annotated[Optional[str], Field(title="Agent Name")] = None
    class_name: Annotated[Optional[str], Field(title="Class Name")] = None
    state_before: Annotated[Optional[Dict[str, Any]], Field(title="State Before")] = (
        None
    )
    state_after: Annotated[Optional[Dict[str, Any]], Field(title="State After")] = None
    span_state: Annotated[str, Field(title="Span State")]
    update_id: Annotated[Optional[int], Field(title="Update Id")] = 1
    queued_at: Annotated[float, Field(title="Queued At")]


class PromptScorerJudgmentType(BaseModel):
    name: Annotated[str, Field(title="Name")]
    prompt: Annotated[str, Field(title="Prompt")]
    options: Annotated[Optional[Dict[str, float]], Field(title="Options")] = None
    created_at: Annotated[Optional[datetime], Field(title="Created At")] = None
    updated_at: Annotated[Optional[datetime], Field(title="Updated At")] = None


class ScorerDataJudgmentType(BaseModel):
    name: Annotated[str, Field(title="Name")]
    threshold: Annotated[float, Field(title="Threshold")]
    success: Annotated[bool, Field(title="Success")]
    score: Annotated[Optional[float], Field(title="Score")] = None
    reason: Annotated[Optional[str], Field(title="Reason")] = None
    strict_mode: Annotated[Optional[bool], Field(title="Strict Mode")] = None
    evaluation_model: Annotated[
        Optional[Union[List[str], str]], Field(title="Evaluation Model")
    ] = None
    error: Annotated[Optional[str], Field(title="Error")] = None
    additional_metadata: Annotated[
        Optional[Dict[str, Any]], Field(title="Additional Metadata")
    ] = None


class TraceUsageJudgmentType(BaseModel):
    prompt_tokens: Annotated[Optional[int], Field(title="Prompt Tokens")] = None
    completion_tokens: Annotated[Optional[int], Field(title="Completion Tokens")] = None
    cache_creation_input_tokens: Annotated[
        Optional[int], Field(title="Cache Creation Input Tokens")
    ] = None
    cache_read_input_tokens: Annotated[
        Optional[int], Field(title="Cache Read Input Tokens")
    ] = None
    total_tokens: Annotated[Optional[int], Field(title="Total Tokens")] = None
    prompt_tokens_cost_usd: Annotated[
        Optional[float], Field(title="Prompt Tokens Cost Usd")
    ] = None
    completion_tokens_cost_usd: Annotated[
        Optional[float], Field(title="Completion Tokens Cost Usd")
    ] = None
    total_cost_usd: Annotated[Optional[float], Field(title="Total Cost Usd")] = None
    model_name: Annotated[Optional[str], Field(title="Model Name")] = None


class ToolJudgmentType(BaseModel):
    tool_name: Annotated[str, Field(title="Tool Name")]
    parameters: Annotated[Optional[Dict[str, Any]], Field(title="Parameters")] = None
    agent_name: Annotated[Optional[str], Field(title="Agent Name")] = None
    result_dependencies: Annotated[
        Optional[List[Dict[str, Any]]], Field(title="Result Dependencies")
    ] = None
    action_dependencies: Annotated[
        Optional[List[Dict[str, Any]]], Field(title="Action Dependencies")
    ] = None
    require_all: Annotated[Optional[bool], Field(title="Require All")] = None


class HTTPValidationErrorJudgmentType(BaseModel):
    detail: Annotated[
        Optional[List[ValidationErrorJudgmentType]], Field(title="Detail")
    ] = None


class JudgmentEvalJudgmentType(BaseModel):
    project_name: Annotated[Optional[str], Field(title="Project Name")] = None
    eval_name: Annotated[Optional[str], Field(title="Eval Name")] = None
    examples: Annotated[List[ExampleJudgmentType], Field(title="Examples")]
    scorers: Annotated[List[ScorerConfigJudgmentType], Field(title="Scorers")]
    model: Annotated[str, Field(title="Model")]
    append: Annotated[Optional[bool], Field(title="Append")] = False
    override: Annotated[Optional[bool], Field(title="Override")] = False
    trace_span_id: Annotated[Optional[str], Field(title="Trace Span Id")] = None
    trace_id: Annotated[Optional[str], Field(title="Trace Id")] = None


class DatasetInsertExamplesJudgmentType(BaseModel):
    dataset_alias: Annotated[str, Field(title="Dataset Alias")]
    examples: Annotated[List[ExampleJudgmentType], Field(title="Examples")]
    project_name: Annotated[str, Field(title="Project Name")]


class SpansBatchRequestJudgmentType(BaseModel):
    spans: Annotated[List[SpanBatchItemJudgmentType], Field(title="Spans")]
    organization_id: Annotated[str, Field(title="Organization Id")]


class FetchPromptScorerResponseJudgmentType(BaseModel):
    scorer: PromptScorerJudgmentType


class TraceSpanJudgmentType(BaseModel):
    span_id: Annotated[str, Field(title="Span Id")]
    trace_id: Annotated[str, Field(title="Trace Id")]
    function: Annotated[str, Field(title="Function")]
    depth: Annotated[int, Field(title="Depth")]
    created_at: Annotated[Any, Field(title="Created At")] = None
    parent_span_id: Annotated[Optional[str], Field(title="Parent Span Id")] = None
    span_type: Annotated[Optional[str], Field(title="Span Type")] = "span"
    inputs: Annotated[Optional[Dict[str, Any]], Field(title="Inputs")] = None
    error: Annotated[Optional[Dict[str, Any]], Field(title="Error")] = None
    output: Annotated[Any, Field(title="Output")] = None
    usage: Optional[TraceUsageJudgmentType] = None
    duration: Annotated[Optional[float], Field(title="Duration")] = None
    expected_tools: Annotated[
        Optional[List[ToolJudgmentType]], Field(title="Expected Tools")
    ] = None
    additional_metadata: Annotated[
        Optional[Dict[str, Any]], Field(title="Additional Metadata")
    ] = None
    has_evaluation: Annotated[Optional[bool], Field(title="Has Evaluation")] = False
    agent_name: Annotated[Optional[str], Field(title="Agent Name")] = None
    class_name: Annotated[Optional[str], Field(title="Class Name")] = None
    state_before: Annotated[Optional[Dict[str, Any]], Field(title="State Before")] = (
        None
    )
    state_after: Annotated[Optional[Dict[str, Any]], Field(title="State After")] = None
    update_id: Annotated[Optional[int], Field(title="Update Id")] = 1


class TraceJudgmentType(BaseModel):
    trace_id: Annotated[str, Field(title="Trace Id")]
    name: Annotated[str, Field(title="Name")]
    created_at: Annotated[str, Field(title="Created At")]
    duration: Annotated[float, Field(title="Duration")]
    trace_spans: Annotated[List[TraceSpanJudgmentType], Field(title="Trace Spans")]
    offline_mode: Annotated[Optional[bool], Field(title="Offline Mode")] = False
    rules: Annotated[Optional[Dict[str, Any]], Field(title="Rules")] = {}
    has_notification: Annotated[Optional[bool], Field(title="Has Notification")] = False
    customer_id: Annotated[Optional[str], Field(title="Customer Id")] = None
    tags: Annotated[Optional[List[str]], Field(title="Tags")] = []
    metadata: Annotated[Optional[Dict[str, Any]], Field(title="Metadata")] = {}
    update_id: Annotated[Optional[int], Field(title="Update Id")] = 1


class ScoringResultJudgmentType(BaseModel):
    success: Annotated[bool, Field(title="Success")]
    scorers_data: Annotated[
        Optional[List[ScorerDataJudgmentType]], Field(title="Scorers Data")
    ] = None
    name: Annotated[Optional[str], Field(title="Name")] = None
    data_object: Annotated[
        Optional[Union[TraceSpanJudgmentType, ExampleJudgmentType]],
        Field(title="Data Object"),
    ] = None
    trace_id: Annotated[Optional[str], Field(title="Trace Id")] = None
    run_duration: Annotated[Optional[float], Field(title="Run Duration")] = None
    evaluation_cost: Annotated[Optional[float], Field(title="Evaluation Cost")] = None


class TraceRunJudgmentType(BaseModel):
    project_name: Annotated[Optional[str], Field(title="Project Name")] = None
    eval_name: Annotated[Optional[str], Field(title="Eval Name")] = None
    traces: Annotated[List[TraceJudgmentType], Field(title="Traces")]
    scorers: Annotated[List[ScorerConfigJudgmentType], Field(title="Scorers")]
    model: Annotated[str, Field(title="Model")]
    append: Annotated[Optional[bool], Field(title="Append")] = False
    override: Annotated[Optional[bool], Field(title="Override")] = False
    trace_span_id: Annotated[Optional[str], Field(title="Trace Span Id")] = None
    tools: Annotated[Optional[List[Dict[str, Any]]], Field(title="Tools")] = None


class EvalResultsJudgmentType(BaseModel):
    results: Annotated[List[ScoringResultJudgmentType], Field(title="Results")]
    run: Annotated[
        Union[TraceRunJudgmentType, JudgmentEvalJudgmentType], Field(title="Run")
    ]


class DatasetPushJudgmentType(BaseModel):
    dataset_alias: Annotated[str, Field(title="Dataset Alias")]
    comments: Annotated[Optional[str], Field(title="Comments")] = None
    source_file: Annotated[Optional[str], Field(title="Source File")] = None
    examples: Annotated[
        Optional[List[ExampleJudgmentType]], Field(title="Examples")
    ] = None
    traces: Annotated[Optional[List[TraceJudgmentType]], Field(title="Traces")] = None
    is_trace: Annotated[Optional[bool], Field(title="Is Trace")] = False
    project_name: Annotated[str, Field(title="Project Name")]
    overwrite: Annotated[Optional[bool], Field(title="Overwrite")] = False
