from __future__ import annotations

import multiprocessing
import random
import sys

import pytest
from opentelemetry.trace import INVALID_SPAN_ID, INVALID_TRACE_ID

from judgeval.trace.id_generator import IsolatedRandomIdGenerator


def test_generates_unique_span_ids():
    gen = IsolatedRandomIdGenerator()
    ids = {gen.generate_span_id() for _ in range(1000)}
    assert len(ids) == 1000


def test_generates_unique_trace_ids():
    gen = IsolatedRandomIdGenerator()
    ids = {gen.generate_trace_id() for _ in range(1000)}
    assert len(ids) == 1000


def test_span_id_never_invalid():
    gen = IsolatedRandomIdGenerator()
    for _ in range(1000):
        assert gen.generate_span_id() != INVALID_SPAN_ID


def test_trace_id_never_invalid():
    gen = IsolatedRandomIdGenerator()
    for _ in range(1000):
        assert gen.generate_trace_id() != INVALID_TRACE_ID


def test_immune_to_global_seed():
    gen = IsolatedRandomIdGenerator()
    random.seed(42)
    ids_seeded = [gen.generate_span_id() for _ in range(10)]
    random.seed(42)
    ids_seeded_again = [gen.generate_span_id() for _ in range(10)]
    assert ids_seeded != ids_seeded_again


def test_different_instances_produce_different_sequences():
    g1 = IsolatedRandomIdGenerator()
    g2 = IsolatedRandomIdGenerator()
    ids1 = [g1.generate_trace_id() for _ in range(10)]
    ids2 = [g2.generate_trace_id() for _ in range(10)]
    assert ids1 != ids2


# ---------------------------------------------------------------------------
# Fork-safety regression test
#
# Reproduces the production failure mode: IsolatedRandomIdGenerator is
# instantiated in the parent process (as Tracer.init() does at app startup),
# then multiple worker processes are forked. Before the os.urandom() fix,
# forked processes inherited identical random.Random state and produced
# colliding IDs. This test catches any regression back to that behaviour.
# ---------------------------------------------------------------------------


def _worker_generate_ids(
    gen: IsolatedRandomIdGenerator, queue: multiprocessing.Queue, count: int = 50
) -> None:
    ids = [gen.generate_trace_id() for _ in range(count)]
    queue.put(ids)


@pytest.mark.skipif(
    sys.platform != "linux", reason="fork-safety test requires POSIX fork"
)
def test_fork_safe_no_id_collisions():
    """IDs generated by forked workers must not collide with each other.

    The generator is created *before* the fork (matching Tracer.init() at
    application startup) to ensure any inherited PRNG state would be exposed.
    """
    n_workers = 4
    ids_per_worker = 50

    # Create the generator in the parent — same as Tracer.init() at startup.
    gen = IsolatedRandomIdGenerator()

    ctx = multiprocessing.get_context("fork")
    queue: multiprocessing.Queue = ctx.Queue()

    procs = [
        ctx.Process(target=_worker_generate_ids, args=(gen, queue, ids_per_worker))
        for _ in range(n_workers)
    ]
    for p in procs:
        p.start()
    for p in procs:
        p.join(timeout=10)
        assert p.exitcode == 0, f"Worker exited with code {p.exitcode}"

    all_ids: list[int] = []
    while not queue.empty():
        all_ids.extend(queue.get_nowait())

    assert len(all_ids) == n_workers * ids_per_worker, (
        "Not all workers returned results"
    )
    assert len(all_ids) == len(set(all_ids)), (
        f"Fork-safety failure: {len(all_ids) - len(set(all_ids))} duplicate trace IDs "
        "across forked worker processes"
    )
