# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional, List, Union, Any, Dict
from typing_extensions import NotRequired


class BaseScorer(TypedDict):
    score_type: str
    name: str
    class_name: NotRequired[Optional[str]]
    score: NotRequired[Optional[float]]
    minimum_score_range: NotRequired[Optional[float]]
    maximum_score_range: NotRequired[Optional[float]]
    score_breakdown: NotRequired[Optional[Dict[str, Any]]]
    reason: NotRequired[Optional[Union[str, Dict[str, Any]]]]
    success: NotRequired[Optional[bool]]
    model: NotRequired[Optional[str]]
    error: NotRequired[Optional[str]]
    additional_metadata: NotRequired[Optional[Dict[str, Any]]]
    user: NotRequired[Optional[str]]
    server_hosted: NotRequired[Optional[bool]]
    using_native_model: NotRequired[Optional[bool]]
    required_params: NotRequired[Optional[List[str]]]
    strict_mode: NotRequired[Optional[bool]]
