# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional, List, Any, Dict
from typing_extensions import NotRequired


class CreateTestConfigRequest(TypedDict):
    name: str
    description: NotRequired[Optional[str]]
    dataset_id: NotRequired[Optional[str]]
    dataset_name: NotRequired[Optional[str]]
    judge_ids: NotRequired[Optional[List[str]]]
    judges: NotRequired[Optional[List[Dict[str, Any]]]]
