# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, List, Any, Dict


class PreparedTestRunResponse(TypedDict):
    test_run: Dict[str, Any]
    dataset: Dict[str, Any]
    dataset_version: Dict[str, Any]
    examples: List[Dict[str, Any]]
    judges: List[Dict[str, Any]]
    evaluation_runs: List[Dict[str, Any]]
    ui_results_url: str
