# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional, List, Any, Dict
from typing_extensions import NotRequired


class SDKCreateAgentJudgeRequest(TypedDict):
    name: str
    judge_description: NotRequired[Optional[str]]
    description: NotRequired[Optional[str]]
    model: str
    prompt: str
    score_type: str
    categories: NotRequired[Optional[List[Dict[str, Any]]]]
    min_score: NotRequired[Optional[float]]
    max_score: NotRequired[Optional[float]]
