# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional, List, Any, Dict
from typing_extensions import NotRequired


class SDKUpdateAgentJudgeRequest(TypedDict):
    judge_description: NotRequired[Optional[str]]
    description: NotRequired[Optional[str]]
    model: NotRequired[Optional[str]]
    prompt: NotRequired[Optional[str]]
    score_type: NotRequired[Optional[str]]
    categories: NotRequired[Optional[List[Dict[str, Any]]]]
    min_score: NotRequired[Optional[float]]
    max_score: NotRequired[Optional[float]]
    target_major_version: NotRequired[Optional[float]]
    target_minor_version: NotRequired[Optional[float]]
    source_major_version: NotRequired[Optional[float]]
    source_minor_version: NotRequired[Optional[float]]
