# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional, List, Any, Dict
from typing_extensions import NotRequired


class TestRunItemsResponse(TypedDict):
    results: List[Dict[str, Any]]
    has_more: bool
    next_cursor: NotRequired[Optional[str]]
    ui_results_url: NotRequired[Optional[str]]
