# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional, Any, Dict
from typing_extensions import NotRequired


class TestRunResponse(TypedDict):
    test_run: Dict[str, Any]
    ui_results_url: NotRequired[Optional[str]]
