# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional, List, Any, Dict
from typing_extensions import NotRequired


class TraceSpan(TypedDict):
    organization_id: str
    project_id: str
    user_id: str
    timestamp: str
    trace_id: str
    span_id: str
    parent_span_id: NotRequired[Optional[str]]
    trace_state: NotRequired[Optional[str]]
    span_name: NotRequired[Optional[str]]
    span_kind: NotRequired[Optional[str]]
    service_name: NotRequired[Optional[str]]
    resource_attributes: Dict[str, Any]
    span_attributes: Dict[str, Any]
    duration: str
    status_code: float
    status_message: NotRequired[Optional[str]]
    events: List[Dict[str, Any]]
    links: NotRequired[Optional[str]]
