# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, List


class UntagPromptResponse(TypedDict):
    commit_ids: List[str]
