# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict

from .upload_custom_scorer_bundle_metadata import UploadCustomScorerBundleMetadata


class UploadCustomScorerBundleRequest(TypedDict):
    metadata: UploadCustomScorerBundleMetadata
    bundle: bytes
