# Auto-generated by scripts/api_generator_v1.py
# DO NOT EDIT MANUALLY
from __future__ import annotations

from typing import TypedDict, Optional, List, Any, Dict
from typing_extensions import NotRequired


class UploadCustomScorerBundleMetadata(TypedDict):
    scorer_name: str
    entrypoint_path: str
    requirements_path: NotRequired[Optional[str]]
    class_name: str
    scorer_type: NotRequired[Optional[str]]
    response_type: str
    version: NotRequired[Optional[float]]
    bump_major: NotRequired[Optional[bool]]
    categories: NotRequired[Optional[List[Dict[str, Any]]]]
